/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** A market genome driven by JSON commands. */
export declare class Genome {
  /**
   * Construct a genome handle from a spec JSON (a non-empty `features` and
   * `symbols`). Throws on an invalid spec.
   */
  constructor(specJson: string)
  /**
   * Apply a command envelope (`{"cmd":"...", ...}`) and return the response
   * JSON. Commands: `set_spec`, `feed`, `feed_batch`, `build`, `vector`,
   * `similar`, `cluster`, `anomaly`, `reset`, `version`. Domain errors come
   * back in-band as `{"ok":false,"error":...}`.
   */
  command(cmdJson: string): string
  /** The crate version. */
  version(): string
}
