/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A market genome driven by JSON commands. */
export declare class Genome {
  /**
   * Construct a genome handle from a spec JSON (a non-empty `features` and
   * `symbols`). Throws on an invalid spec.
   */
  constructor(specJson: string)
  /**
   * Apply a command envelope (`{"cmd":"...", ...}`) and return the response
   * JSON. Commands: `set_spec`, `feed`, `feed_batch`, `build`, `vector`,
   * `similar`, `cluster`, `anomaly`, `reset`, `version`. Domain errors come
   * back in-band as `{"ok":false,"error":...}`.
   */
  command(cmdJson: string): string
  /** The crate version. */
  version(): string
}
